apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gb
  labels:
    type: ebs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-YYYYY
    fsType: xfs
