apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rbd-tester 
  name: rbd-tester
spec:
  replicas: 1
  selector:
    name: rbd-tester-rc
  template:
    metadata:
      labels:
        name: rbd-tester-rc
    spec:
      restartPolicy: Always
      containers:
        - image: gcr.io/google_containers/nginx:1.7.9 
          name: rbd-tester
          ports:
           - containerPort: 80
         
          volumeMounts:
            - name: rbdvol
              mountPath: /mnt/rbd
      volumes:
        - name: rbdvol
          persistentVolumeClaim:
           claimName: myclaim

