apiVersion: v1 
kind: PersistentVolume
metadata:
  name: ceph
spec:
  capacity:
   storage: 5Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  rbd:
   monitors: ['172.17.0.2:6789']
   pool: rbd
   image: foo
   user: admin
   secretRef:
     name: 'ceph-secret'
   keyring: ''
   fsType: 'ext4'
   readOnly: false
