apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rbd-tester 
  name: rbd-tester
spec:
  replicas: 1
  selector:
    name: rbd-tester-rc
  template:
    metadata:
      labels:
        name: rbd-tester-rc
    spec:
      restartPolicy: Always
      containers:
        - image: busybox 
          command: ["/bin/sleep","7d"]  
          name: rbd-tester
          volumeMounts:
            - name: rbdvol
              mountPath: /mnt/rbd
      volumes:
        - name: rbdvol
          persistentVolumeClaim:
           claimName: myclaim

